name: Daily Tieba Sign-In

on:
  workflow_dispatch:
  schedule:
    - cron: '20 21 * * *'  # 每天5:20执行 (UTC+8)

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'  # 使用官方推荐的 Maven 依赖缓存
          
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository  # Maven 本地缓存目录
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # 使用 pom.xml 作为缓存 key
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and execute
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          mvn -B compile exec:java \
            -Dexec.mainClass="top.srcrs.Run" \
            -Dexec.args="$BDUSS $SCKEY"
